config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"posts#index"
  resources :users do
    #collection do
     # get 'favorites'
    #end
  end
  resources :posts do
    collection do
      get 'search'
      get 'maps'
      get 'prefecture'
    end
    #collection do
     # get 'favorites'
    #end
    resources :favorites, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end
  #get 'posts/:id', to: 'review#create' 
  #get 'posts/;id', to: 'favorites#create'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true, uniqueness: { scope: :post_id}
  validates :post_id, presence: true

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def index
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)  
  end

  def create
    if @post.user_id != current_user.id
      favorite = current_user.favorites.build(post_id: params[:post_id])
      favorite.save
    end
  end

  def destroy
    #@favorite = Favorite.find(params[:id])
    @favorite = Favorite.find_by(id: params[:id], user_id: current_user.id, post_id: params[:post_id])
    @favorite.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorite_path(post,post.favorite_of(current_user)), method: :delete, remote: :true do %>
      <button type="button" class="btn btn-light">
        <h2><i class="fa fa-star" aria-hidden="true"></i><%= post.favorites.count %></h2>
      </button>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post.id), method: :post, remote: :true do %>
      <button type="button" class="btn btn-light">
        <h2><i class="fa fa-star-o" aria-hidden="true"></i><%= post.favorites.count %></h2>
      </button>
    <% end %>
  <% end %>
<% else %>
  <button type="button" class="btn btn-light">
    <h2><i class="fa fa-star" aria-hidden="true"></i><%= post.favorites.count %></h2>
  </button>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/index.html.erb
<%= render "shared/header" %>
<%# /検索 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <span class="nav-link"><%= link_to "都道府県検索", "#"%></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", "#" %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>
<%# お気に入り一覧%>
<h4><%= link_to "<< TOP", root_path, class: "top_bottun" %></h4>
<h2>お気に入り一覧<h2>
<div class="row">
  <% @favorite_posts.each do |favorite| %>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= link_to favorite.campsite, "#", method: :get %></h4>
        </div>
        <%= link_to post_path(@post.id), method: :get do %>
          <%= image_tag favorite.image, class: "img-fluid" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-subtitle"><%= link_to favorite.user.nickname, "/users/#{@post.user_id}", method: :get %></h5>
        </div>
        <h5 class="card-text"><%= favorite.text %></h5>
      </div>
    </div>
  <% end %>
</div>
<%= render "shared/footer" %>