config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"posts#index"
  resources :users do
    #collection do
     # get 'favorites'
    #end
  end
  resources :posts do
    collection do
      get 'search'
      get 'maps'
      get 'prefecture'
    end
    #collection do
     # get 'favorites'
    #end
    resources :favorites, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end
  #get 'posts/:id', to: 'review#create' 
  #get 'posts/;id', to: 'favorites#create'
end

app/models/post.rb
class Post < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :place
  belongs_to :toilet
  belongs_to :fire
  belongs_to :river
  belongs_to :gomi
  belongs_to :water

  with_options presence: true do
    validates :image
    validates :text
    validates :place_id
    validates :toilet_id
    validates :fire_id
    validates :river_id
    validates :gomi_id
    validates :water_id
    validates :price, format: {with: /\A[0-9]+\z/ }
    validates :address
    validates :latitude
    validates :longitude
  end

  with_options numericality: { other_than: 1 } do
    validates :place_id
    validates :toilet_id
    validates :fire_id
    validates :river_id
    validates :gomi_id
    validates :water_id
  end

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%").
        or(where('campsite LIKE(?)', "%#{search}%"))
    else
      Post.all
    end
  end

  def self.prefecture(prefecture)
    Post.where(place_id: "#{prefecture}")
  end

  #def favorite(user)
    #favorites.create(user_id: user.id)
  #end

  #def unfavorite(user)
  #  favorites.find_by(user_id: user.id).destroy
  #end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorite_of(user)
    favorite = favorites.find_by(user_id: user.id)
  end

  has_one_attached :image

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :reviews
  has_many :post_tags
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_sing_in, except: [:index, :show, :search, :prefecture]
  before_action :move_to_index, only: [:edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes([:user, :favorites]).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @post.reviews.includes(:user)
    #results = Geocoder.search(params[:address])
    #@latlng = results.first.coordinates
  end

  def edit
    
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  #def favorites
   # @favorite = Favorite.find(params[:id])
   # @favorite_posts = current_user.favorite_posts.includes(:user).order(created_at: :desc)
  #end

  def prefecture
    @place = Place.find(params[:place_id])
    @posts = Post.prefecture(params[:place_id]).order("created_at DESC")
  end

  def maps
    @posts = Post.includes([:user, :favorites])
  end

  private

  def move_to_sing_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def move_to_index
    unless current_user.id == @post.user_id
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit(:campsite, :text, :place_id, :toilet_id, :water_id, :fire_id, :gomi_id, :river_id, :price, :image, :favorite_count, :address, :latitude, :longitude).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/favorites.html.erb
<%= render "shared/header" %>
<%# /検索 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", "#" %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>
<h4><%= link_to "<< BACK", :back, class: "back_bottun" %></h4>
<h2>お気に入り一覧<h2>
<%# /お気に入り一覧 %>
<div class='post-contents'>
  <ul class='post-lists'>
  <%# if user_signed_in? && current_user.id == @favorite_posts.user_id %>
    <% @favorite_posts.each do |post| %>
    <li class='list'>
      <div class='post-campsite'>
        <%= link_to post.campsite, "#", method: :get %>
      </div>
      <%= link_to post_path(post.id), method: :get do %>
      <div class='post-img-content'>
        <%= image_tag post.image, class: "post-img" %>
      </div>
      <div class='post-info'>
        <div class='user_name'>
          <%= link_to post.user.nickname, "/users/#{post.user_id}", method: :get %>
        </div>
        <div id="favo_buttons_<%= post.id %>">
          <%= render partial: 'favorites/favorite', locals: { post: post} %>
        </div>
        <div class='post_text'>
          <%= post.text %>
        </div>
        <div class='post_tag'>
          <%#=　"タグ"　%>
        </div>
      </div>
      <% end %>
    </li>
    <% end %>
  <%# end %>
  </ul>
</div>

<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<%# /検索 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", maps_posts_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(@posts) %></span>
      </li>
    </ul>
  </div>
</nav>
<%# /投稿一覧 %>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to post.campsite, "#", method: :get %>
          </h4>
        </div>
        <%= link_to post_path(post.id), method: :get do %>
          <%= image_tag post.image, class: "img-fluid" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-subtitle">@<%= link_to post.user.nickname, "/users/#{post.user_id}", method: :get %></h5>
          <div id="favorites_buttons_<%= post.id %>">
             <%= render partial: 'favorites/favorite', locals: { post: post} %>
          </div>
          <h5 class="card-text"><%= post.text %></h5>
        </div>
      </div>
    </div>
  <% end%>
</div>

<%= render "shared/footer" %>

app/views/posts/maps.html.erb
<%= render "shared/header" %>
<%# /検索 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", maps_posts_path %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>

<h2>MAP</h2>
<div id="map"></div>
<style type="text/css">
  #map {
    height: 700px;
    width: 80%;
  }
</style>

<script>
  function initMap(){
    map = new google.maps.Map(document.getElementById("map"),{
      center: {lat: 36.0000, lng:138.0000},
      zoom: 12
    });
    '<% @posts.each do |post| %>'
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    let contentString = '<%= post.campsite %>：<%= post.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    let geocoder = new google.maps.Geocoder();
    geocoder.geocode({address: '<%= post.address %>'},function(results,status){
      if (status == 'OK'){
        let marker = new google.maps.Marker({
          position: results[0].geometry.location,
          map: map,
          title: contentString
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      };
    })
    '<% end %>'
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5IBI1uKD_cvsflrRSl-LVDhxdWjeZNFQ&callback=initMap" async defer ></script>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<%# 投稿情報%>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", "#" %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>

<h2>NEW POST</h2>
<%= form_with(model: @post, local: true) do |f| %>
  <form>
    <div class="form-group">
      <label for="post-image">Picture(必須)</label>
      <%= f.file_field :image, id:"post-image" %>
    </div>
    <div class="form-group">
      <label for="campsite">キャンプ場名(必須)</label>
      <%= f.text_area :campsite, class:"post-text", id:"campsite", placeholder:"キャンプ場名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <div class="form-group">
      <label for="post-info">コメント</label>
      <%= f.text_area :text, class:"post-text", id:"post-info", placeholder:"コメント（1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <div class="form-group">
      <label for="post-place">場所(必須)</label>
      <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"select-box", id:"post-place"}) %>
    </div>
    <div class="form-group">
      <label for="post-info">住所</label>
      <%= f.text_field :address, id:"post-address", placeholder: "都道府県から" %>
    </div>
    <div class="form-group">
      <label for="post-toilet">トイレ(必須)</label>
      <%= f.collection_select(:toilet_id, Toilet.all, :id, :name, {}, {class:"select-box", id:"post-toilet"}) %>
    </div>
    <div class="form-group">
      <label for="post-water">水道(必須)</label>
      <%= f.collection_select(:water_id, Water.all, :id, :name, {}, {class:"select-box", id:"post-water"}) %>
    </div>
    <div class="form-group">
      <label for="post-fire">火(必須)</label>
      <%= f.collection_select(:fire_id, Fire.all, :id, :name, {}, {class:"select-box", id:"post-fire"}) %>
    </div>
    <div class="form-group">
      <label for="post-gomi">ごみ捨て場(必須)</label>
      <%= f.collection_select(:gomi_id, Gomi.all, :id, :name, {}, {class:"select-box", id:"post-gomi"}) %>
    </div>
    <div class="form-group">
      <label for="post-river">立地(必須)</label>
      <%= f.collection_select(:river_id, River.all, :id, :name, {}, {class:"select-box", id:"post-river"}) %>
    </div> 
    <div class="form-group">
      <label for="post-price">サイト料(必須)</label>
      <span class="sell-yen">¥</span>
      <%= f.text_field :price, class:"price-input", id:"post-price", placeholder:"例）1000" %>
    </div>
    <div class="form-group row">
      <%= f.submit "POST" ,class:"btn btn-primary" %>
    </div>
  </form>
<% end %>


<%= render "shared/footer" %>

app/views/posts/prefecture.html.erb
<%= render "shared/header" %>

<%# 投稿の概要 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", "#" %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>

<h4><%= link_to "<< TOP", root_path, class: "top_bottun" %></h4>

<h2><%= @place.name %>にあるキャンプ場一覧</h2>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to post.campsite, "#", method: :get %>
          </h4>
        </div>
        <%= link_to post_path(post.id), method: :get do %>
          <%= image_tag post.image, class: "img-fluid" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-subtitle">@<%= link_to post.user.nickname, "/users/#{post.user_id}", method: :get %></h5>
          <div id="favorites_buttons_<%= post.id %>">
             <%= render partial: 'favorites/favorite', locals: { post: post} %>
          </div>
          <h5 class="card-text"><%= post.text %></h5>
        </div>
      </div>
    </div>
  <% end%>
</div>
<%= render "shared/footer" %>

app/views/posts/search.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "検索", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to post.campsite, "#", method: :get %>
          </h4>
        </div>
        <%= link_to post_path(post.id), method: :get do %>
          <%= image_tag post.image, class: "img-fluid" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-subtitle"><%= link_to post.user.nickname, "/users/#{post.user_id}", method: :get %></h5>
          <div id="favorites_buttons_<%= post.id %>">
             <%= render partial: 'favorites/favorite', locals: { post: post} %>
          </div>
          <h5 class="card-text"><%= post.text %></h5>
        </div>
      </div>
    </div>
  <% end%>
</div>


<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<%# 投稿の概要 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワード検索", class: "form-control mr-sm-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">都道府県検索</a>
        <%= render "posts/prefecture" %>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "マップ検索", "#" %></span>
      </li>
      <li class="nav-item">
        <span class="nav-link"><%= link_to "お気に入り一覧", post_favorites_path(current_user.id) %></span>
      </li>
    </ul>
  </div>
</nav>
<h4><%= link_to "<< TOP", root_path, class: "top_bottun" %></h4>
<div class="container">
  <div class="col-8 center">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"><%= @post.campsite %></h3>
      </div>
        <%= image_tag @post.image ,class:"img-fluid" %>
      <div class="card-body">
        <h4 class="card-title">@<%= link_to @post.user.nickname, "/users/#{@post.user_id}", method: :get %></h4>
        <div class="d-inline" id="favorites_buttons_<%= @post.id %>">
          <%= render partial: 'favorites/favorite', locals: { post: @post} %>
        </div>
        <p class="card-text"><%= @post.text %></p>
      </div>
    </div>
  </div>

  <div class="col-6 ml-2">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th scope="row" >場所</th>
          <td><%= @post.place.name %></td>
        </tr>
        <tr>
          <th scope="row">住所</th>
          <td><%= @post.address %></td>
        </tr>
        <tr>
          <th scope="row">トイレ</th>
          <td><%= @post.toilet.name %></td>
        </tr>
        <tr>
          <th scope="row">水道</th>
          <td><%= @post.water.name %></td>
        </tr>
        <tr>
          <th scope="row">ゴミ</th>
          <td><%= @post.gomi.name %></td>
        </tr>
        <tr>
          <th scope="row">たき火</th>
          <td><%= @post.fire.name %></td>
        </tr>
        <tr>
          <th scope="row">立地</th>
          <td><%= @post.river.name %></td>
        </tr>
        <tr>
          <th scope="row">サイト料</th>
          <td>¥<%= @post.price%></td>
        </tr>
      </tbody>
    </table>
  </div>

  <h2>MAP</h2>
  <div id="map"></div>
  <style type="text/css">
  #map {
    height: 300px;
    width: 70%;
  }
  </style>

  <script>
  function initMap(){
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    let contentString = '<%= @post.campsite %>：<%= @post.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    let geocoder = new google.maps.Geocoder();
    geocoder.geocode({address: '<%= @post.address %>'},function(results,status){
      if (status == 'OK'){
        map = new google.maps.Map(document.getElementById("map"),{
          center: results[0].geometry.location,
          zoom: 12
        });
        let marker = new google.maps.Marker({
          position: results[0].geometry.location,
          map: map,
          title: contentString
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      };
    })
  }
  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API']%>&callback=initMap" async defer ></script>



  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">レビュー</button>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" rola=dialog aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="model-header">
          <h5 class="modal-title" id="exampleModalLabel">レビュー投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with(model: [@post,@review], local: true) do |f| %>
          <div class="form-group">
            <label for="formGroupleInput">訪問日</label>
            <%= f.date_field :visit_day, id:"date-info" %>
          </div>
          <div class="form-group">
            <label for="formGroupleInput">コメント</label>
            <%= f.text_area :comment, class:"form-control", id:"formGroupExampleInput", placeholder:"コメント（1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
          </div>
          <div class="form-group">
            <label for="formGroupleInput">写真</label>
            <%= f.file_field :image, id:"post-image" %>
          </div>
        </div>
        <div class="modeal-footer actions">
          <%= f.submit "投稿", class:"btn btn-primary justtify-content-end" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <% if user_signed_in? && current_user.id == @post.user_id %>
    <button type="button" class="btn-danger d-inline"><%= link_to '編集', edit_post_path, method: :get %></button>
    <button type="button" class="btn-danger d-inline"><%= link_to '削除', post_path, method: :delete %></button>
  <% end %>

  <h3 class = "font-weight-bold" >みんなのキャン活</h3>
  <div class="overflow-auto col-8" style="height:40vh;">
    <% @reviews.each do |review| %>
      <div class = "card" >
        <div class = "card-body" >
          <P class="card-tittle d-inline"><%= link_to review.user.nickname, "/users/#{review.user_id}", method: :get %></P>
          <p class="card-text d-inline"><%= review.visit_day %></P>
          <p class="card-text"><%= review.comment %></p>
        </div>
      </div>
    <% end %>
  </div>

  <h3 class = "font-weight-bold">みんなの写真</h3>
  <div class="row">
    <% @reviews.each do |review| %>
      <% if review.image.present? %>
        <div class="img-thumbnail　d-inline-block m-1">
          <%= image_tag review.image, :size =>'200x200'%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>